name: book_audio_app
description: "Ứng dụng đọc sách và nghe audiobook của Bảo"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Cấu hình tương thích rộng rãi với Flutter 3.x

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Thư viện gọi API từ FastAPI
  http: ^1.2.0

  # Thư viện chọn trực tiếp tệp (Ảnh, PDF, MP3) từ bộ nhớ thiết bị
  file_picker: ^8.0.0

  # Thư viện phát âm thanh cho Audiobook
  audioplayers: ^6.6.0

  # Thư viện hiển thị ảnh bìa sách từ URL và lưu tạm (cache)
  cached_network_image: ^3.3.0

  # Hỗ trợ quản lý trạng thái đơn giản (nếu cần)
  provider: ^6.1.1
  flutter_pdfview: ^1.4.4
  path_provider: ^2.1.5
  image_picker: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Khai báo tài nguyên Assets cục bộ trong ứng dụng (Nếu Bảo cần dùng sau này)
  #assets:
    #- assets/images/
    #- assets/audios/